name: Deploy project
on: [push]

jobs:
  deploy:
    runs-on: bndhost1
    steps:
      - uses: actions/checkout@v2
      - name: Pull containers
        run: docker-compose pull -q
      - name: Deploy services
        run: docker-compose up -d